"""OWNER: M3 (Interview Prep & Intelligence)

Built-in skill knowledge used by the RULE-BASED engine (no AI needed):
  - aliases  : different spellings of the same skill ("k8s" -> Kubernetes)
  - category : language / framework / database / tool / cloud / testing / ai / concept
  - topics   : interview topics to prepare for that skill

Add new skills here and every feature (JD analyzer, resume match, prep plan) picks them up.
"""

SKILLS = {
    # ---- languages
    "Python": {"aliases": ["python", "python3"], "category": "language",
               "topics": ["OOP", "Decorators", "Generators", "Exception Handling", "Comprehensions",
                          "Iterators & Closures", "Context Managers", "GIL & Memory Management"]},
    "Java": {"aliases": ["java", "core java"], "category": "language",
             "topics": ["OOP Concepts", "Collections Framework", "Exception Handling", "Multithreading",
                        "Streams & Lambdas", "JVM Internals"]},
    "JavaScript": {"aliases": ["javascript", "ecmascript", "es6"], "category": "language",
                   "topics": ["Closures", "Promises & async/await", "Event Loop", "Prototypes", "ES6+ Features"]},
    "TypeScript": {"aliases": ["typescript"], "category": "language",
                   "topics": ["Types vs Interfaces", "Generics", "Type Narrowing"]},
    # ---- databases
    "SQL": {"aliases": ["sql"], "category": "database",
            "topics": ["Joins", "Indexes", "Transactions", "Normalization", "Group By & Aggregates",
                       "Window Functions", "Subqueries"]},
    "PostgreSQL": {"aliases": ["postgresql", "postgres"], "category": "database",
                   "topics": ["Indexes & Query Plans", "Transaction Isolation", "JSONB", "Vacuum"]},
    "MySQL": {"aliases": ["mysql"], "category": "database",
              "topics": ["Storage Engines", "Indexes", "Joins"]},
    "MongoDB": {"aliases": ["mongodb", "mongo db"], "category": "database",
                "topics": ["Document Modelling", "Aggregation Pipeline", "Indexes"]},
    "Redis": {"aliases": ["redis"], "category": "database",
              "topics": ["Caching Patterns", "Data Types", "Persistence"]},
    # ---- frameworks
    "FastAPI": {"aliases": ["fastapi", "fast api"], "category": "framework",
                "topics": ["Dependency Injection", "Middleware", "Authentication", "Pydantic Validation",
                           "Async Endpoints"]},
    "Django": {"aliases": ["django"], "category": "framework",
               "topics": ["ORM", "Middleware", "Signals", "Django REST Framework"]},
    "Flask": {"aliases": ["flask"], "category": "framework",
              "topics": ["Blueprints", "Request Context", "Extensions"]},
    "React": {"aliases": ["react", "reactjs", "react.js"], "category": "framework",
              "topics": ["Hooks", "State Management", "Component Lifecycle", "Virtual DOM"]},
    "Node.js": {"aliases": ["node.js", "nodejs", "node js"], "category": "framework",
                "topics": ["Event Loop", "Streams", "Express Middleware"]},
    # ---- testing
    "Playwright": {"aliases": ["playwright"], "category": "testing",
                   "topics": ["Fixtures", "Locators", "Auto-waiting", "Page Object Model",
                              "Network Interception", "Parallel Execution"]},
    "Selenium": {"aliases": ["selenium", "selenium webdriver"], "category": "testing",
                 "topics": ["Implicit vs Explicit Waits", "Locators", "WebDriver Architecture",
                            "Page Object Model", "Selenium Grid"]},
    "Pytest": {"aliases": ["pytest"], "category": "testing",
               "topics": ["Fixtures", "Parametrization", "Markers", "conftest.py"]},
    "API Testing": {"aliases": ["api testing", "api automation", "rest assured", "restassured"],
                    "category": "testing",
                    "topics": ["HTTP Methods & Status Codes", "Authentication", "Response Validation",
                               "Contract Testing"]},
    "Test Automation": {"aliases": ["test automation", "automation testing", "automated testing",
                                    "qa automation", "automation framework"],
                        "category": "testing",
                        "topics": ["Framework Design", "Page Object Model", "Data-driven Testing",
                                   "CI Integration"]},
    "Manual Testing": {"aliases": ["manual testing"], "category": "testing",
                       "topics": ["Test Cases & Test Plans", "Bug Life Cycle", "STLC"]},
    "Postman": {"aliases": ["postman"], "category": "tool",
                "topics": ["Collections", "Environments", "Pre-request Scripts", "Newman"]},
    # ---- tools / devops / cloud
    "REST API": {"aliases": ["rest api", "rest apis", "restful", "restful api", "restful apis"],
                 "category": "concept",
                 "topics": ["REST Principles", "Idempotency", "Status Codes", "Versioning", "Pagination"]},
    "Docker": {"aliases": ["docker", "containerization"], "category": "tool",
               "topics": ["Images vs Containers", "Dockerfile", "Volumes", "Docker Compose", "Networking"]},
    "Kubernetes": {"aliases": ["kubernetes", "k8s"], "category": "tool",
                   "topics": ["Pods & Deployments", "Services", "ConfigMaps & Secrets", "Scaling"]},
    "AWS": {"aliases": ["aws", "amazon web services"], "category": "cloud",
            "topics": ["EC2", "S3", "IAM", "Lambda", "RDS"]},
    "Azure": {"aliases": ["azure", "microsoft azure"], "category": "cloud",
              "topics": ["App Service", "Blob Storage", "Azure AD", "Functions"]},
    "GCP": {"aliases": ["gcp", "google cloud"], "category": "cloud",
            "topics": ["Compute Engine", "Cloud Storage", "IAM", "Cloud Functions"]},
    "Git": {"aliases": ["git", "github", "gitlab"], "category": "tool",
            "topics": ["Branching Strategies", "Merge vs Rebase", "Resolving Conflicts"]},
    "CI/CD": {"aliases": ["ci/cd", "ci cd", "cicd", "continuous integration"], "category": "tool",
              "topics": ["Pipelines", "Deployment Strategies", "Test Automation in Pipelines"]},
    "Jenkins": {"aliases": ["jenkins"], "category": "tool",
                "topics": ["Pipelines", "Jenkinsfile", "Agents & Nodes"]},
    "Terraform": {"aliases": ["terraform"], "category": "tool",
                  "topics": ["State", "Modules", "Providers"]},
    "Linux": {"aliases": ["linux", "unix", "shell scripting", "bash"], "category": "tool",
              "topics": ["File Permissions", "Processes", "Shell Scripting", "Networking Commands"]},
    "DevOps": {"aliases": ["devops"], "category": "concept",
               "topics": ["CI/CD", "Infrastructure as Code", "Monitoring"]},
    # ---- AI / data
    "GenAI": {"aliases": ["genai", "gen ai", "generative ai"], "category": "ai",
              "topics": ["Prompt Engineering", "LLM Basics", "RAG", "Evaluating LLM Outputs", "Hallucinations"]},
    "LLM": {"aliases": ["llm", "llms", "large language model", "large language models"], "category": "ai",
            "topics": ["Tokens & Context Window", "Fine-tuning vs RAG", "Prompting", "Evaluation"]},
    "RAG": {"aliases": ["rag", "retrieval augmented generation", "retrieval-augmented generation"],
            "category": "ai",
            "topics": ["Embeddings", "Vector Databases", "Chunking", "Retrieval Strategies"]},
    "Prompt Engineering": {"aliases": ["prompt engineering", "prompting"], "category": "ai",
                           "topics": ["Zero/Few-shot", "Chain of Thought", "Prompt Evaluation"]},
    "LangChain": {"aliases": ["langchain", "langgraph"], "category": "ai",
                  "topics": ["Chains", "Agents", "Memory", "Retrievers"]},
    "Agentic AI": {"aliases": ["agentic ai", "ai agents", "agentic"], "category": "ai",
                   "topics": ["Agent Loops", "Tool Calling", "Planning & Memory"]},
    "Machine Learning": {"aliases": ["machine learning"], "category": "ai",
                         "topics": ["Supervised vs Unsupervised", "Overfitting", "Evaluation Metrics",
                                    "Feature Engineering"]},
    "Data Science": {"aliases": ["data science", "data scientist"], "category": "ai",
                     "topics": ["Statistics", "Data Cleaning", "Visualization", "Model Evaluation"]},
    "Pandas": {"aliases": ["pandas"], "category": "framework",
               "topics": ["DataFrames", "Merging & Joining", "GroupBy", "Data Cleaning"]},
    # ---- concepts
    "System Design": {"aliases": ["system design", "high level design", "low level design"],
                      "category": "concept",
                      "topics": ["REST API Design", "Caching", "Scaling", "Load Balancing", "Database Sharding"]},
    "Microservices": {"aliases": ["microservices", "microservice"], "category": "concept",
                      "topics": ["Service Communication", "API Gateway", "Fault Tolerance"]},
    "Agile": {"aliases": ["agile", "scrum"], "category": "concept",
              "topics": ["Scrum Ceremonies", "User Stories", "Sprint Planning"]},
}

GENERIC_TOPICS = ["Core concepts", "Common interview questions", "Hands-on practice"]

# categories treated as "tools" in the JD analyzer output
TOOL_CATEGORIES = {"tool", "cloud", "testing"}
