const API = '';
const STATUSES = ['SAVED','APPLIED','APPLICATION_VIEWED','SHORTLISTED','HR_CONTACTED','INTERVIEW_SCHEDULED','INTERVIEW_1','INTERVIEW_2','HR_ROUND','ON_HOLD','OFFER_RECEIVED','ACCEPTED','DECLINED','REJECTED'];
const BOARD = ['SAVED','APPLIED','HR_CONTACTED','INTERVIEW_SCHEDULED','OFFER_RECEIVED','ACCEPTED','REJECTED'];
const NEXT = {SAVED:['APPLIED'],APPLIED:['APPLICATION_VIEWED','SHORTLISTED','HR_CONTACTED','REJECTED'],APPLICATION_VIEWED:['SHORTLISTED','REJECTED'],SHORTLISTED:['HR_CONTACTED','REJECTED'],HR_CONTACTED:['INTERVIEW_SCHEDULED','REJECTED'],INTERVIEW_SCHEDULED:['INTERVIEW_1','ON_HOLD','REJECTED'],INTERVIEW_1:['INTERVIEW_2','HR_ROUND','ON_HOLD','REJECTED'],INTERVIEW_2:['HR_ROUND','ON_HOLD','REJECTED'],HR_ROUND:['OFFER_RECEIVED','ON_HOLD','REJECTED'],ON_HOLD:['INTERVIEW_1','INTERVIEW_2','HR_ROUND','REJECTED'],OFFER_RECEIVED:['ACCEPTED','DECLINED']};
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user = null, applications = [], currentView = 'board', activeId = null;
const token = () => localStorage.getItem('careertrack_token');
async function api(path, options={}) {
  const headers = {'Content-Type':'application/json', ...(options.headers||{})};
  if (token()) headers.Authorization = `Bearer ${token()}`;
  const res = await fetch(`${API}${path}`, {...options, headers});
  if (res.status === 204) return null;
  const body = await res.json().catch(()=>({detail:'Unexpected server response'}));
  if (!res.ok) throw new Error(body.detail || `Request failed (${res.status})`);
  return body;
}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2600)}
function date(value){if(!value)return 'Date not set';return new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function statusTitle(s){return s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function start(){if(!token()){showLogin();return}$('#admin-nav').classList.add('hidden');try{user=await api('/auth/me');$('#user-name').textContent=user.name;$('#logout').classList.remove('hidden');if(user.role==='ADMIN')$('#admin-nav').classList.remove('hidden');$('#login-view').classList.add('hidden');$('#workspace').classList.remove('hidden');await load()}catch{localStorage.removeItem('careertrack_token');showLogin()}}
function showLogin(){$('#workspace').classList.add('hidden');$('#login-view').classList.remove('hidden')}
async function load(){try{applications=await api('/applications?limit=200');render()}catch(e){toast(e.message)}}
function render(){ $('#page-title').textContent=currentView==='board'?'Your board':currentView==='list'?'All applications':'Application analytics';$('#page-subtitle').textContent=currentView==='board'?'A clear view of what’s moving and what needs attention.':currentView==='list'?'Every role and its latest status.': 'Patterns across your applications and interviews.';document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));renderSummary(); if(currentView==='board')renderBoard();else if(currentView==='list')renderList();else renderAnalytics() }
function renderSummary(){const submitted=applications.filter(a=>a.status!=='SAVED').length, interviews=applications.filter(a=>a.status.includes('INTERVIEW')||a.status==='HR_ROUND').length, offers=applications.filter(a=>['OFFER_RECEIVED','ACCEPTED'].includes(a.status)).length;$('#summary').innerHTML=[['Tracked roles',applications.length],['Applications sent',submitted],['In interview',interviews],['Offers',offers]].map(([l,n])=>`<div class="metric"><span>${l}</span><strong>${n}</strong></div>`).join('')}
function appCard(a){return `<article class="app-card" data-id="${a.id}"><h3>${esc(a.job_title)}</h3><p>${esc(a.company_name||'Company not set')}${a.location?' · '+esc(a.location):''}</p><div class="card-foot"><span>${esc(a.source||'CareerTrack')}</span><span>${date(a.applied_date||a.created_at)}</span></div></article>`}
function renderBoard(){const groups=[['Saved',['SAVED']],['Applied',['APPLIED','APPLICATION_VIEWED','SHORTLISTED','HR_CONTACTED']],['Interview',['INTERVIEW_SCHEDULED','INTERVIEW_1','INTERVIEW_2','HR_ROUND','ON_HOLD']],['Decision',['OFFER_RECEIVED','ACCEPTED','DECLINED','REJECTED']]];$('#content').innerHTML=`<div class="board">${groups.map(([name,statuses])=>{let items=applications.filter(a=>statuses.includes(a.status));return `<section class="column"><div class="column-head"><h3>${name}</h3><span class="count">${items.length}</span></div>${items.length?items.map(appCard).join(''):'<div class="empty">No applications here yet</div>'}</section>`}).join('')}</div>`;bindCards()}
function renderList(){$('#content').innerHTML=applications.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Role</th><th>Company</th><th>Status</th><th>Applied</th><th>Source</th></tr></thead><tbody>${applications.map(a=>`<tr class="row-link" data-id="${a.id}"><td><strong>${esc(a.job_title)}</strong></td><td>${esc(a.company_name||'—')}</td><td><span class="badge">${esc(statusTitle(a.status))}</span></td><td>${date(a.applied_date)}</td><td>${esc(a.source||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="panel empty">Your applications will appear here.</div>';bindCards()}
async function renderAnalytics(){try{const d=await api('/dashboard/analytics'),statuses=Object.entries(d.by_status||{});$('#content').innerHTML=`<div class="analytics-grid"><section class="analytics-box"><h3>Application → response</h3><strong>${d.response_rate}%</strong><div class="bar"><i style="width:${Math.min(d.response_rate,100)}%"></i></div></section><section class="analytics-box"><h3>Response → interview</h3><strong>${d.response_to_interview_rate}%</strong><div class="bar"><i style="width:${Math.min(d.response_to_interview_rate,100)}%"></i></div></section><section class="analytics-box"><h3>Interview → offer</h3><strong>${d.interview_to_offer_rate}%</strong><div class="bar"><i style="width:${Math.min(d.interview_to_offer_rate,100)}%"></i></div></section><section class="analytics-box"><h3>By status</h3>${statuses.length?statuses.map(([s,n])=>`<div class="bar-row"><span>${esc(statusTitle(s))}</span><div class="bar"><i style="width:${d.total_applications?Math.max(n*100/d.total_applications,3):0}%"></i></div><b>${n}</b></div>`).join(''):'No data yet'}</section><section class="analytics-box"><h3>Applications by source</h3>${Object.entries(d.by_source||{}).map(([s,n])=>`<div class="bar-row"><span>${esc(s)}</span><div class="bar"><i style="width:${d.total_applications?Math.max(n*100/d.total_applications,3):0}%"></i></div><b>${n}</b></div>`).join('')||'No data yet'}</section><section class="analytics-box"><h3>Response rate by source</h3>${Object.entries(d.by_source_response_rate||{}).map(([s,n])=>`<div class="bar-row"><span>${esc(s)}</span><div class="bar"><i style="width:${Math.min(n,100)}%"></i></div><b>${n}%</b></div>`).join('')||'No data yet'}</section><section class="analytics-box"><h3>Interview rounds</h3><strong>${d.interview_rounds}</strong></section><section class="analytics-box"><h3>Upcoming interviews</h3>${(d.upcoming_interviews||[]).map(i=>`<div class="detail-item"><strong>${esc(i.company_name||'Company')} · ${esc(i.job_title)}</strong><small>${esc(i.round_name)} · ${new Date(i.scheduled_at).toLocaleString()}</small></div>`).join('')||'No upcoming interviews'}</section></div>`}catch(e){toast(e.message)}}
function bindCards(){document.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>openDetail(Number(el.dataset.id))))}
async function openDetail(id){
  activeId=id;
  try{
    const [a,timeline,rounds,notes,docs,reminders,hrCalls]=await Promise.all([
      api(`/applications/${id}`),api(`/applications/${id}/timeline`),api(`/interviews/applications/${id}`),
      api(`/notes?application_id=${id}`),api(`/documents?application_id=${id}`),api('/reminders'),api(`/applications/${id}/hr-calls`)
    ]);
    const mine=reminders.filter(r=>r.application_id===id);
    const allowed=[a.status,...(NEXT[a.status]||[])];
    const d=$('#detail');d.classList.remove('hidden');
    d.innerHTML=`<button class="icon-button" id="close-detail" aria-label="Close">×</button>
      <div class="eyebrow">APPLICATION DETAILS</div><h2>${esc(a.job_title)}</h2>
      <div class="sub">${esc(a.company_name||'Company not set')} · ${esc(a.location||'Location not set')}</div>
      <div class="detail-item"><strong>Status</strong><select id="status-select">${allowed.map(s=>`<option value="${s}" ${s===a.status?'selected':''}>${esc(statusTitle(s))}</option>`).join('')}</select></div>
      <div class="detail-item"><strong>Job description</strong><small>${esc(a.jd_text||'No description saved.')}</small></div>
      <button class="small-button" id="prepare-application">Prepare for this application</button>
      <h3 class="section-title">Timeline</h3><div class="timeline">${timeline.events.map(e=>`<div class="event">${e.type==='status'?`Status · ${esc(statusTitle(e.new_status))}`:e.type==='interview'?`${esc(e.round_name)} · ${esc(statusTitle(e.status))}`:esc(e.title||'HR call')}<small>${date(e.changed_at||e.scheduled_at)}${e.comment?' · '+esc(e.comment):''}${e.details?' · '+esc(e.details):''}${e.feedback?' · '+esc(e.feedback):''}</small></div>`).join('')||'<small>No events yet</small>'}</div>
      <form id="timeline-event-form"><input name="title" required maxlength="200" placeholder="Add a timeline event"><input name="event_at" type="datetime-local"><textarea name="details" placeholder="Details"></textarea><button class="small-button">Add event</button></form>
      <h3 class="section-title">Interview rounds</h3>${rounds.map(i=>`<div class="detail-item"><strong>${esc(i.round_name)}</strong><small>${date(i.scheduled_at)} · ${esc(statusTitle(i.status))}<br>${esc(i.interviewer||'Interviewer not set')} · ${esc(i.mode||'Mode not set')}<br>${esc(i.feedback||'Feedback not recorded')}</small><form class="round-update-form" data-round-update="${i.id}"><label>Round status<select name="status"><option ${i.status==='SCHEDULED'?'selected':''}>SCHEDULED</option><option ${i.status==='COMPLETED'?'selected':''}>COMPLETED</option><option ${i.status==='CANCELLED'?'selected':''}>CANCELLED</option><option ${i.status==='NO_SHOW'?'selected':''}>NO_SHOW</option></select></label><label>Scheduled at<input name="scheduled_at" type="datetime-local" value="${i.scheduled_at?new Date(i.scheduled_at).toISOString().slice(0,16):''}"></label><textarea name="feedback" placeholder="Interview feedback">${esc(i.feedback||'')}</textarea><button class="small-button">Update round</button></form></div>`).join('')}
      <button class="small-button" id="add-round">＋ Add round / HR call</button><div id="round-form-slot"></div>
      <h3 class="section-title">HR call history</h3>${hrCalls.map(c=>`<div class="detail-item"><strong>${esc(c.hr_name||'HR call')} · ${date(c.call_at)}</strong><small>${esc(c.company_name||a.company_name||'Company not set')} · ${esc(c.phone||'Phone not recorded')}<br>${esc(c.discussion||'No discussion recorded')}${c.next_round?' · Next: '+esc(c.next_round):''}${c.interview_at?' · Interview: '+date(c.interview_at):''}${c.notes?' · '+esc(c.notes):''}</small></div>`).join('')||'<small>No calls recorded yet.</small>'}
      <form id="hr-call-form"><input name="hr_name" placeholder="HR name"><input name="phone" placeholder="Phone"><input name="call_at" type="datetime-local"><textarea name="discussion" placeholder="Discussion"></textarea><input name="next_round" placeholder="Next round"><input name="interview_at" type="datetime-local"><textarea name="notes" placeholder="Follow-up notes"></textarea><button class="small-button">Save HR call</button></form>
      <h3 class="section-title">Personal notes</h3>${notes.map(n=>`<div class="detail-item"><form class="note-update-form" data-note-update="${n.id}"><input name="title" required value="${esc(n.title)}"><textarea name="content">${esc(n.content||'')}</textarea><button class="small-button">Update note</button><button type="button" class="small-button" data-note-delete="${n.id}">Delete</button></form></div>`).join('')}
      <form id="note-form"><input name="title" required placeholder="Note title"><textarea name="content" placeholder="Add a private note"></textarea><button class="small-button">Save note</button></form>
      <h3 class="section-title">Documents</h3>${docs.map(x=>`<div class="detail-item"><a href="${esc(x.file_url)}" target="_blank" rel="noopener">${esc(x.name)}</a><small>${esc(x.doc_type||'Document')}</small><button type="button" class="small-button" data-document-delete="${x.id}">Remove link</button></div>`).join('')}
      <form id="doc-form"><input name="name" required placeholder="Document name"><input name="file_url" required type="url" placeholder="Secure HTTPS document URL"><input name="doc_type" placeholder="Resume, cover letter…"><button class="small-button">Attach document</button></form>
      <h3 class="section-title">Reminders</h3>${mine.map(r=>`<div class="detail-item">${esc(r.title)}<small>${date(r.reminder_time)} · ${esc(statusTitle(r.status))}</small>${['PENDING','DUE'].includes(r.status)?`<button class="small-button" data-reminder-done="${r.id}">Mark done</button>`:''}</div>`).join('')}
      <form id="reminder-form"><input name="title" required placeholder="Follow up with recruiter"><input name="reminder_time" required type="datetime-local"><button class="small-button">Set reminder</button></form>`;
    $('#close-detail').onclick=closeDetail;
    $('#prepare-application').onclick=()=>{chosenApplication=id;chosenJob=null;currentView='prep';closeDetail();render()};
    $('#timeline-event-form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));if(v.event_at)v.event_at=new Date(v.event_at).toISOString();else delete v.event_at;try{await api(`/applications/${id}/events`,{method:'POST',body:JSON.stringify(v)});await openDetail(id)}catch(err){toast(err.message)}};
    $('#hr-call-form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));for(const key of ['call_at','interview_at'])if(v[key])v[key]=new Date(v[key]).toISOString();else delete v[key];try{await api(`/applications/${id}/hr-calls`,{method:'POST',body:JSON.stringify(v)});await openDetail(id)}catch(err){toast(err.message)}};
    document.querySelectorAll('[data-round-update]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form));if(v.scheduled_at)v.scheduled_at=new Date(v.scheduled_at).toISOString();else v.scheduled_at=null;try{await api(`/interviews/${form.dataset.roundUpdate}`,{method:'PUT',body:JSON.stringify(v)});await openDetail(id)}catch(err){toast(err.message)}});
    document.querySelectorAll('[data-note-update]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form));try{await api(`/notes/${form.dataset.noteUpdate}`,{method:'PUT',body:JSON.stringify(v)});await openDetail(id)}catch(err){toast(err.message)}});
    document.querySelectorAll('[data-note-delete]').forEach(button=>button.onclick=async()=>{try{await api(`/notes/${button.dataset.noteDelete}`,{method:'DELETE'});await openDetail(id)}catch(err){toast(err.message)}});
    document.querySelectorAll('[data-document-delete]').forEach(button=>button.onclick=async()=>{try{await api(`/documents/${button.dataset.documentDelete}`,{method:'DELETE'});await openDetail(id)}catch(err){toast(err.message)}});
    $('#status-select').onchange=async e=>{try{await api(`/applications/${id}/status`,{method:'POST',body:JSON.stringify({status:e.target.value})});await load();await openDetail(id)}catch(err){toast(err.message);e.target.value=a.status}};
    $('#add-round').onclick=()=>{
      $('#round-form-slot').innerHTML=`<form id="round-form"><input name="round_name" required placeholder="Technical round / HR call"><input name="scheduled_at" type="datetime-local"><input name="interviewer" placeholder="Interviewer"><select name="mode"><option value="VIDEO">Video</option><option value="PHONE">Phone</option><option value="ONSITE">On site</option></select><input name="meeting_link" type="url" placeholder="Meeting link"><textarea name="feedback" placeholder="Notes or feedback"></textarea><button class="small-button">Save round</button></form>`;
      $('#round-form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));if(v.scheduled_at)v.scheduled_at=new Date(v.scheduled_at).toISOString();else delete v.scheduled_at;try{await api(`/interviews/applications/${id}`,{method:'POST',body:JSON.stringify(v)});await load();await openDetail(id)}catch(err){toast(err.message)}};
    };
    $('#note-form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));try{await api('/notes',{method:'POST',body:JSON.stringify({...v,application_id:id})});await openDetail(id)}catch(err){toast(err.message)}};
    $('#doc-form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));if(!v.doc_type)delete v.doc_type;try{await api('/documents',{method:'POST',body:JSON.stringify({...v,application_id:id})});await openDetail(id)}catch(err){toast(err.message)}};
    $('#reminder-form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.reminder_time=new Date(v.reminder_time).toISOString();try{await api('/reminders',{method:'POST',body:JSON.stringify({...v,application_id:id})});await openDetail(id)}catch(err){toast(err.message)}};
    document.querySelectorAll('[data-reminder-done]').forEach(b=>b.onclick=async()=>{try{await api(`/reminders/${b.dataset.reminderDone}`,{method:'PUT',body:JSON.stringify({status:'COMPLETED'})});await openDetail(id)}catch(err){toast(err.message)}});
    if(!document.querySelector('.detail-backdrop')){const backdrop=document.createElement('div');backdrop.className='detail-backdrop';document.body.append(backdrop);backdrop.onclick=closeDetail}
  }catch(e){toast(e.message)}
}
function closeDetail(){$('#detail').classList.add('hidden');document.querySelector('.detail-backdrop')?.remove();activeId=null}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const form=Object.fromEntries(new FormData(e.target));try{const data=await api('/auth/login/json',{method:'POST',body:JSON.stringify(form)});localStorage.setItem('careertrack_token',data.access_token);await start()}catch(err){$('#login-error').textContent=err.message}});
$('#logout').onclick=()=>{localStorage.removeItem('careertrack_token');user=null;$('#logout').classList.add('hidden');closeDetail();showLogin()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;closeDetail();render()});
$('#add-application').onclick=()=>$('#application-dialog').showModal();$('#close-dialog').onclick=()=>$('#application-dialog').close();
$('#application-form').addEventListener('submit',async e=>{e.preventDefault();$('#form-error').textContent='';const v=Object.fromEntries(new FormData(e.target));try{await api('/applications',{method:'POST',body:JSON.stringify(v)});$('#application-dialog').close();e.target.reset();await load();toast('Application saved')}catch(err){$('#form-error').textContent=err.message}});
start();
