from enum import Enum


class Role(str, Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class JobStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CLOSED = "CLOSED"


class ApplicationStatus(str, Enum):
    SAVED = "SAVED"
    APPLIED = "APPLIED"
    APPLICATION_VIEWED = "APPLICATION_VIEWED"
    SHORTLISTED = "SHORTLISTED"
    HR_CONTACTED = "HR_CONTACTED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_1 = "INTERVIEW_1"
    INTERVIEW_2 = "INTERVIEW_2"
    HR_ROUND = "HR_ROUND"
    OFFER_RECEIVED = "OFFER_RECEIVED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    ON_HOLD = "ON_HOLD"
    DECLINED = "DECLINED"


class SkillImportance(str, Enum):
    REQUIRED = "REQUIRED"
    PREFERRED = "PREFERRED"
    OPTIONAL = "OPTIONAL"
